update yaml file to debugginh

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -52,6 +52,19 @@ jobs:
       - name: Install Dependencies
         run: npm install
 
+      - name: Debug Runner Environment
+        run: |
+            echo "Node version:"
+            node -v
+            echo "NPM version:"
+            npm -v
+            echo "PM2 path:"
+            which pm2 || echo "pm2 not found"
+            echo "Current directory:"
+            pwd
+            echo "List files:"
+            ls -R
+            
       - name: Start Application
         run: |
           export PATH=$PATH:/usr/bin:/usr/local/bin
